/**********************************************************************************************************************
 * \file ApplicationFramework.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef APPLICATIONFRAMEWORK_C_
#define APPLICATIONFRAMEWORK_C_

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "ApplicationFramework.h"
#include "PRINTS_driver.h"
#include "BatteryRead.h"
#include "Ccu6Source.h"
#include "BatteryRead.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
ApplicationConfig BmsDefaultAppConfig = {

        .EnableTestCounter          =  BMS_HACK_DISABLED,
        .EnableBlinkLedTest         =  BMS_HACK_DISABLED,
        .EnableAdcConversionTask    =  BMS_HACK_ENABLED,

};
/*********************************************************************************************************************/
/*-------------------------------------------------Data Structures---------------------------------------------------*/
/*********************************************************************************************************************/
 
/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
int ApplicationFramework_Init(ApplicationConfig* AppConfig){

    int result = 0;
    int state=0;

    // Initialization for the ADC conversion task
    if(AppConfig->EnableAdcConversionTask == BMS_HACK_ENABLED){
            Sync_Enable();
            usr_printf(2, "\nSync Enabled \n");
    }



    // Initialize the ASCLIN module for uart based prints
    #if(ENABLE_ASCLIN_PRINTS == BMS_HACK_ENABLED)
        ASC_init();
    #endif

    // Enable Test counter
    if(AppConfig->EnableTestCounter == BMS_HACK_ENABLED)
        MEMTESTCOUNTER = 0x0;

    // Enable BlinkLed
    if(AppConfig->EnableBlinkLedTest == BMS_HACK_ENABLED){
        result |= BlinkLed_Init(&LedPinConfig);

        #if(ENABLE_ASCLIN_PRINTS == BMS_HACK_ENABLED)
                usr_printf(2, "\nBlinkLed_Init Done\n");
            #endif

    }

    // Enable CCU6 and EVADC based task
    if(AppConfig->EnableAdcConversionTask == BMS_HACK_ENABLED){

        //For Synchronization with the Battery Emulator
         Aurix_Ready_Acknowledge_to_battery();

        #if(ENABLE_ASCLIN_PRINTS == BMS_HACK_ENABLED)
             usr_printf(2, "\nAurix Ready Acknowledge has been sent to Battery Emulator \n");
        #endif

         state = Battery_Ready__Acknowledge_to_Aurix();


        #if(ENABLE_ASCLIN_PRINTS == BMS_HACK_ENABLED)
             usr_printf(2, "\nRead the Acknowledge from the Battery \n");
        #endif

         while(state != 1){

        #if(ENABLE_ASCLIN_PRINTS == BMS_HACK_ENABLED)
             usr_printf(2, "\nBattery Acknowledge is not high still \n");
        #endif


         state = Battery_Ready__Acknowledge_to_Aurix();
         };

         result |=  InitAdcConversionTask();

         #if(ENABLE_ASCLIN_PRINTS == BMS_HACK_ENABLED)
               usr_printf(2, "\nADC Conversion Task Initialized \n");
             #endif

     }


   return result;


}


int ApplicationFramework_Run(ApplicationConfig* AppConfig){

    int result = 0;



    if(AppConfig->EnableTestCounter == BMS_HACK_ENABLED)
            MEMTESTCOUNTER = MEMTESTCOUNTER + 1;


    if(AppConfig->EnableBlinkLedTest == BMS_HACK_ENABLED)
           result |= BlinkLed_Run(&LedPinConfig);

    if(AppConfig->EnableAdcConversionTask == BMS_HACK_ENABLED){

        BatteryRead_Enable();
        result |= StartAdcConversionTask();

    }

    return result;

}


int ApplicationFramework_PostProcess(ApplicationConfig* AppConfig){

    int result = 0;

    return result;

}



// Driver Function for executing the application

int ApplicationFramework_Execute(void){

    int result = 0;

    // FrameworkInitializatuib required only once
    result |= ApplicationFramework_Init(&BmsDefaultAppConfig);


    // Framework Run and post process in an infinite loop

    while(BMS_HACK_ENABLED){

        result |=  ApplicationFramework_Run(&BmsDefaultAppConfig);
        result |=  ApplicationFramework_PostProcess(&BmsDefaultAppConfig);


        // Add a fail condition to the future monitor structure
        if(result != 0x0){
                return result;
        }


        // This has an impact on the periodicity of the application

        // First two options are basically to set the repeatability of other tasks

        if(BMS_DELAY_TYPE == BMS_DELAY_MS)
            IfxStm_waitTicks(&MODULE_STM0,IfxStm_getTicksFromMilliseconds(&MODULE_STM0, APPLICATION_ITERATION_DELAY_MS));
        else if(BMS_DELAY_TYPE == BMS_DELAY_US)
            IfxStm_waitTicks(&MODULE_STM0,IfxStm_getTicksFromMicroseconds(&MODULE_STM0, APPLICATION_ITERATION_DELAY_US));
        else if(BMS_WAIT_ADC_INT)
        {
            //Waiting for ADC and Timer Interrupts
            while(1);
        }


    }


    return result;

}

#endif /* APPLICATIONFRAMEWORK_C_ */
