/**********************************************************************************************************************
 * \file BlinkLed.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "BatteryRead.h"
#include "BugInjection.h"
#include "ifxPort.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

// Initial handshake with the battery emulator
// Battery emulator waits after start till this pin becomes high
// Once this signal is received, battery emulator then waits for the pin to become low
// Once this pin becomes low, battery emulator starts charging/discharging

void Aurix_Ready_Acknowledge_to_battery(void)
{
        IfxPort_setPinModeOutput(&MODULE_P33, 0, IfxPort_OutputMode_openDrain, IfxPort_OutputIdx_general);
        IfxPort_setPinHigh(&MODULE_P33, 0);
        usr_printf(2, "\nAurix_Ready_Acknowledge_to_battery Sync Sent\n");

}


// Handshake received from the battery emulator that release the aurix during init
int Battery_Ready__Acknowledge_to_Aurix(void)
{
    int state=0;

    IfxPort_setPinModeInput(&MODULE_P33, 1, IfxPort_InputMode_pullUp);
    state= IfxPort_getPinState(&MODULE_P33, 1);

    return state;
}



// Pulling down this pin starts the discharge/charge process
void BatteryRead_Enable(void)
{

    IfxPort_setPinModeOutput(&MODULE_P33, 2, IfxPort_OutputMode_openDrain, IfxPort_OutputIdx_general);
    IfxPort_setPinLow(&MODULE_P33, 2);

}


void Sync_Enable(void)
{
    // Handshake pin from Aurix to battery emulator
    IfxPort_setPinModeOutput(&MODULE_P33, 0, IfxPort_OutputMode_openDrain, IfxPort_OutputIdx_general);
    // Initial state for the handshake pin
    IfxPort_setPinLow(&MODULE_P33, 0);

    // Set the charge/discharge status pin as input
    IfxPort_setPinModeInput(&MODULE_P33, 2, IfxPort_InputMode_pullUp);



}

void BatteryRead_Disable(void)
{
    int timeout = 150000000;
    IfxPort_setPinModeOutput(&MODULE_P33, 0, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
    IfxPort_setPinLow(&MODULE_P33, 0);

}


