/**********************************************************************************************************************
 * \file Ccu6Source.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Ccu6Source.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/


/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
/* Timer handle */
IfxCcu6_Timer g_timer;
/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

/* Function to initialize the CCU6 module */
void init_CCU6(void)
{
    IfxCcu6_Timer_Config timerConfig;
    IfxCcu6_Timer_initModuleConfig(&timerConfig, &MODULE_CCU60);

    /* Configure the T12 timer frequency/period (trigger for T13 timer) and T13 timer frequency/period (trigger
     * for ADC). Timer T13 starts counting in single shot mode triggered by a period-match event of the T12 timer.
     * The period of the timer T13 represents a delay (from the period-match event of the T12 timer) of the ADC
     * trigger event.
     */
    timerConfig.base.t12Frequency = CCU6_T12_TIMER_FREQ;                /* Timer T12 frequency                      */
    timerConfig.base.waitingTime = CCU6_T12_TIMER_PERIOD;               /* waitingTime is the period of T12 timer   */
    timerConfig.base.t13Frequency = CCU6_T13_TIMER_FREQ;                /* Timer T13 frequency                      */
    timerConfig.base.t13Period = CCU6_T13_TIMER_PERIOD;                 /* Timer T13 period                         */
    timerConfig.timer = IfxCcu6_TimerId_t13;                            /* Select the timer, T13 is the master      */
    timerConfig.synchronousOperation = FALSE;                           /* Disable synchronous start of the timers  */
    timerConfig.trigger.t13InSyncWithT12 = TRUE;                        /* T12 timer starts the T13 timer           */

    /* Configure the T13 timer start event */
    timerConfig.timer13.t12SyncEvent = IfxCcu6_T13TriggerEvent_onT12Period;
    timerConfig.timer13.t12SyncDirection = IfxCcu6_T13TriggerDirection_onT12CountingUp;

    /* Apply the configuration to the CCU6 module */
    IfxCcu6_Timer_initModule(&g_timer, &timerConfig);

    /* Activate the line ServiceRequest_3 to route the T13 period match event trigger to the EVADC module */
    IfxCcu6_enableInterrupt(&MODULE_CCU60, IfxCcu6_InterruptSource_t13PeriodMatch);
    IfxCcu6_routeInterruptNode(&MODULE_CCU60, IfxCcu6_InterruptSource_t13PeriodMatch, IfxCcu6_ServiceRequest_3);

    /* Configure the T13 timer for single shot mode */
    IfxCcu6_enableSingleShotMode(&MODULE_CCU60, IfxCcu6_TimerId_t13);
}

/* Function to start the CCU6 timer, according to the configuration */
void start_CCU6_timer(void)
{
    IfxCcu6_Timer_start(&g_timer);
}
