/**********************************************************************************************************************
 * \file EvadcSource.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "EvadcSource.h"
#include "ApplicationFrameworkConfig.h"
#include "BugInjection.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
 /* EVADC handle */
IfxEvadc_Adc         g_evadc;
IfxEvadc_Adc_Group   g_adcGroup;
IfxEvadc_Adc_Channel g_adcChannel;

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

/* Function to initialize the EVADC module with default parameters */
void init_EVADC_module()
{
    /* Create configuration */
    IfxEvadc_Adc_Config adcConfig;
    IfxEvadc_Adc_initModuleConfig(&adcConfig, &MODULE_EVADC);

    /* Initialize module */
    IfxEvadc_Adc_initModule(&g_evadc, &adcConfig);
}

/* Function to initialize the EVADC group */
void init_EVADC_group()
{
    /* Create and initialize group configuration with default values */
    IfxEvadc_Adc_GroupConfig adcGroupConfig;
    IfxEvadc_Adc_initGroupConfig(&adcGroupConfig, &g_evadc);

    /* Setting user configuration using group 0 */
    adcGroupConfig.groupId = ADC_GROUP;
    adcGroupConfig.master = adcGroupConfig.groupId;

    /* Enable queue 0 source */
    adcGroupConfig.arbiter.requestSlotQueue0Enabled = TRUE;

    /* Enable all gates in "always" mode (no edge detection) */
    adcGroupConfig.queueRequest[0].triggerConfig.gatingMode = IfxEvadc_GatingMode_always;

    /* Configure the EVADC module to trigger a conversion based on CCU6 timer period match event */
    /* Trigger 0 is connected to CCU6 ServiceRequest_3 line */
    adcGroupConfig.queueRequest[0].triggerConfig.triggerSource = IfxEvadc_TriggerSource_0;

    /* Select the trigger event type */
    adcGroupConfig.queueRequest[0].triggerConfig.triggerMode = IfxEvadc_TriggerMode_uponRisingEdge;

    /* Set that requests with higher priority cancel a running lower priority conversion */
    adcGroupConfig.queueRequest[0].requestSlotStartMode = IfxEvadc_RequestSlotStartMode_cancelInjectRepeat;

    /* Initialize the group */
    IfxEvadc_Adc_initGroup(&g_adcGroup, &adcGroupConfig);
}

/* Function to initialize the EVADC channel */
void init_EVADC_channels()
{
    /* Create channel configuration */
    IfxEvadc_Adc_ChannelConfig adcChannelConfig;

    IfxEvadc_Adc_initChannelConfig(&adcChannelConfig, &g_adcGroup);

    adcChannelConfig.channelId = (IfxEvadc_ChannelId)(ADC_CHANNEL);
    adcChannelConfig.resultRegister = (IfxEvadc_ChannelResult)(ADC_CHANNEL);

    /* Interrupt for sending the data via UART */
    adcChannelConfig.resultPriority = ISR_PRIORITY_ADC;                 /* Set the EVADC interrupt priority          */
    adcChannelConfig.resultServProvider = IfxSrc_Tos_cpu0;              /* Set the EVADC interrupt service provider  */

    /* Initialize the channel */
    IfxEvadc_Adc_initChannel(&g_adcChannel, &adcChannelConfig);

    /* Add channel to queue with refill and external trigger enabled */
    IfxEvadc_Adc_addToQueue(&g_adcChannel, IfxEvadc_RequestSource_queue0, (ENABLE_EXTERNAL_TRIGGER | IFXEVADC_QUEUE_REFILL));
}



/* Function to initialize the EVADC with default parameters */
void init_EVADC()
{
    init_EVADC_module();    /* Initialize the EVADC module */
    init_EVADC_group();     /* Initialize the EVADC group  */
    init_EVADC_channels();  /* Initialize the channels     */
}




/* ADC Interrupt Service Routine */
IFX_INTERRUPT(ISR_ADC_result, 0, ISR_PRIORITY_ADC);

void ISR_ADC_result(void)
{
    /* Get the result from the EVADC result register and print it using the UART communication */
    Ifx_EVADC_G_RES conversionResult = IfxEvadc_Adc_getResult(&g_adcChannel);
    uint16 adcValue = conversionResult.B.RESULT;

//Why am I needed? May be this is intentional bug. Think smart
   /* if((FrameworkSoCMonitor_Slow.LatestCurrentSampleNumber)==10||(FrameworkSoCMonitor_Slow.LatestCurrentSampleNumber== 15)||(FrameworkSoCMonitor_Slow.LatestCurrentSampleNumber== 20))
    {
        conversionResult.B.RESULT =0x384;
    }
*/

    #if(ENABLE_ASCLIN_PRINTS == BMS_HACK_ENABLED)
        usr_printf(2, "\n ADC Sample: %d\r\n", conversionResult.B.RESULT);
    #endif


    #if(BMS_APP_BATTERY_PROFILE == BATTERY_PROFILE_ACTIVE_SLOW)

        FrameworkSoCMonitor_Slow.LatestCurrentSampleNumber++;

        // Used for testing purpose only
         #if(BMS_APP_INJECT_CURRENT_SURGE == BMS_HACK_ENABLED)
            if(FrameworkSoCMonitor_Slow.LatestCurrentSampleNumber == BMS_APP_INJECT_SURGE_SAMPLE_NUMBER)
                conversionResult.B.RESULT =  conversionResult.B.RESULT * 100;
        #endif

        UpdateSoCValue( &(FrameworkSoCMonitor_Slow) , (conversionResult.B.RESULT/BMS_APP_CURRENT_CONVERSION_FACTOR));

        #if(ENABLE_ASCLIN_PRINTS == BMS_HACK_ENABLED)
               usr_printf(2, "\n Sample Number : %d Current Received : %d mA \r\n",FrameworkSoCMonitor_Slow.LatestCurrentSampleNumber,\
                       conversionResult.B.RESULT/BMS_APP_CURRENT_CONVERSION_FACTOR);
               usr_printf(2, "\n Battery Charge Percentage : %d percent \r\n ",FrameworkSoCMonitor_Slow.CurrentSoCVal);
           #endif
    #endif


}

