/**********************************************************************************************************************
 * \file SoCMonitor.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "SoCMonitor.h"
#include "ApplicationFrameworkConfig.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

// Initial value of the SoCMonitor
// This SoC monitor provides initializations and battery parameters to the algorithm

#if(BMS_APP_BATTERY_PROFILE == BATTERY_PROFILE_ACTIVE_SLOW)

            SoCMonitor FrameworkSoCMonitor_Slow ={
                           // Battery Capacity in mAs
                           .BatteryCapacity = 5000,
                           // Initial State of Charge Value as a percentage
                           .InitialSoCVal =   100,
                           // Current State of Charge Value as a percentage
                           .CurrentSoCVal =   100,
                           // Time-step for sampling in seconds, a new current sample is obtained at every TimeStep delta
                           .TimeStep =  1,
                           // The most recent current sample time-stamp
                           .LatestCurrentSampleNumber = 0,
                   };

#endif



    /*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

// Function to update and calculate the SoC Value
// Function called from EVADCSource.c
int UpdateSoCValue(SoCMonitor* SCM, float ReceivedCurrentValue){

    // Determine the charge/discharge scenario based on the output from battery emulator

    int BatteryChargeState = 0;

    BatteryChargeState =  IfxPort_getPinState(&MODULE_P33, 2); //Use the pin which helps for identifying charging and discaharging state

              
    if (BatteryChargeState == 1)
        {
            SCM->CurrentSoCVal += (100 * ((SCM->TimeStep * ReceivedCurrentValue) / SCM->BatteryCapacity));
        }
        else
        {
            SCM->CurrentSoCVal -= (100 * ((SCM->TimeStep * ReceivedCurrentValue) / SCM->BatteryCapacity));
        }

        return SCM->CurrentSoCVal;

}
